# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
        exclude: auto/helm/training-portal/templates
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: requirements-txt-fixer
-   repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        exclude_types: [json]
        args: ["-L", "connexion", "--skip=*.map,*.js"]
#-   repo: https://github.com/asottile/yesqa
    #rev: v1.3.0
    #hooks:
      #- id: yesqa
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
-   repo: https://github.com/asottile/blacken-docs
    rev: 1.18.0
    hooks:
    -   id: blacken-docs
-   repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
    -   id: autoflake
        name: autoflake
        args: ["--in-place", "--remove-unused-variables", "--remove-all-unused-imports"]
        language: python
        files: \.py$
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
    -   id: flake8
        args:
          - "--max-line-length=110"
          - "--max-complexity=15"
-   repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
#-   repo: https://github.com/pre-commit/mirrors-mypy
    #rev: v0.950
    #hooks:
      #- id: mypy
        #exclude: ^(docs/|example-plugin/)
        #additional_dependencies: [types-toml==0.10.4, types-requests]
#-   repo: https://github.com/PyCQA/bandit
    #rev: 1.7.4
    #hooks:
      #- id: bandit
        #name: bandit
        #description: 'Bandit is a tool for finding common security issues in Python code'
        #entry: bandit
        #language: python
        #language_version: python3
        #types: [python]
        #args: [ "--configfile", "/home/rogue/source/pyatt-dev/bandit.yaml" ]
-   repo: local
    hooks:
      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: pytest --cov-config=.coveragerc --cov --cov-fail-under=30
        pass_filenames: false
        always_run: true
