[code]
directory = "/home/rogue/source/pyatt-dev"

[pods]

    [pods.training-portal]
    # helm install --set ingress.enabled=true --description "Training Portal" training-portal training-portal/
    name = "training-portal"
    desc = "Training Portal"
    version = "0.0.8"
    active = true
    command = "helm install"
    command_args = "--set ingress.enabled=true"
    helm_directory = "training-portal"
    code_path = "/home/rogue/source/pyatt-dev"
    seed_command = "loaddb.py"


# Images we want preloaded in the local container registry
[images]
images = [
        'training-portal:0.0.8',
        'mysql:8.0',
        'proxysql/proxysql:2.3.2',
        'minio/minio:RELEASE.2022-09-01T23-53-36Z'
    ]

# Specific service settings
[mysql]
active = true
databases = ['dev_training']

[minio]
active = true

[proxysql]
active = true
