[code]
directory = "/home/rogue/source/devocho"

[pods]

    [pods.portal]
    # helm install --set ingress.enabled=true --description "Portal" portal portal/
    name = "portal"
    desc = "Portal"
    version = "0.0.8"
    active = true
    command = "helm install"
    command_args = "--set ingress.enabled=true"
    seed_command = "loaddb.py"


# Images we want preloaded in the local container registry
[images]
images = [
        'mysql:8.0',
        'proxysql/proxysql:2.3.2',
        'minio/minio:RELEASE.2022-09-01T23-53-36Z'
    ]

# Specific service settings
[mysql]
active = true
databases = ['dev_training']

[minio]
active = true

[proxysql]
active = true
