apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
spec:
  selector:
    matchLabels:
      app: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql
    spec:
      securityContext:
        fsGroup: 10001
      initContainers:
      - name: volume-permissions
        image: busybox:latest
        securityContext:
          runAsUser: 0
        # Ensure the volume is owned by the mssql user (10001)
        command: ["sh", "-c", "chown -R 10001:0 /var/opt/mssql && chmod 700 /var/opt/mssql"]
        volumeMounts:
        - name: mssql-persistent-storage
          mountPath: /var/opt/mssql
      containers:
      - image: mcr.microsoft.com/mssql/server:2022-latest
        name: mssql
        resources:
          requests:
            memory: "2Gi"
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: "Developer"
        - name: MSSQL_SA_PASSWORD
          value: "P@ssword123!"
        ports:
        - containerPort: 1433
          name: mssql
        volumeMounts:
        - name: mssql-persistent-storage
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-persistent-storage
        persistentVolumeClaim:
          claimName: mssql-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pv-claim
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - port: 1433
    targetPort: 1433
    nodePort: 30034
    protocol: TCP
    name: mssql
  selector:
    app: mssql
