name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  # Required for creating releases and uploading artifacts

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install flake8 pytest pyinstaller
        if [ -f build_requirements.txt ]; then pip install -r build_requirements.txt; fi

    - name: Lint with flake8
      run: |
        source venv/bin/activate
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=./venv/*
        flake8 . --count --exit-zero --max-complexity=12 --max-line-length=127 --statistics --exclude=./venv/*

    - name: Test with pytest
      run: |
        source venv/bin/activate
        pytest

    - name: Build with pyinstaller
      run: |
        source venv/bin/activate
        pyinstaller --onefile --name auto --add-data "venv/lib/python3.12/site-packages/pyfiglet/fonts:pyfiglet/fonts" auto.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: auto-executable
        path: dist/auto
        if-no-files-found: error

    - name: Create GitHub Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v0.4.${{ github.run_number }}
        name: Release v0.4.${{ github.run_number }}
        draft: false
        prerelease: false
        files: dist/auto
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
